# Automatically generated by Pynguin.
from notebook import config_manager as module0


def test_case_0():
    var0 = '.invalid'
    var1 = {var0: var0, var0: var0}
    var2 = module0.BaseJSONConfigManager(**var1)
    assert var2 is not None
    var3 = {var2: var1}
    var4 = ()
    var5 = module0.remove_defaults(var3, var4)
    assert var5 is None
    var6 = var2.ensure_config_dir_exists()
    assert var6 is None
