# Automatically generated by Pynguin.
import conftest as module0


def test_case_0():
    try:
        var0 = b''
        var1 = {var0, var0}
        var2 = [var0, var1]
        var3 = '\nUtilities for file-based Contents/Checkpoints managers.\n'
        var4 = module0.pytest_ignore_collect(var3)
        assert var4 is None
        var5 = {var1: var2, var1: var2, var2: var1, var1: var0}
    except BaseException:
        pass
